language: c
sudo: false
env:
  global:
    - RACKET_DIR=~/racket
  matrix:
    - RACKET_VERSION=6.4
    - RACKET_VERSION=6.5
    - RACKET_VERSION=6.6
    - RACKET_VERSION=6.7
    - RACKET_VERSION=6.8
    - RACKET_VERSION=6.9
    - RACKET_VERSION=6.10
    - RACKET_VERSION=HEAD

before_install:
  - git clone https://github.com/greghendershott/travis-racket.git ../travis-racket
  - cat ../travis-racket/install-racket.sh | bash
  - export PATH="${RACKET_DIR}/bin:${PATH}"
  - raco pkg install --auto cover cover-codecov doc-coverage

install:
  - raco pkg install --auto
      $TRAVIS_BUILD_DIR/arguments
      $TRAVIS_BUILD_DIR/mock
      $TRAVIS_BUILD_DIR/mock-rackunit

script:
  - raco test -p arguments mock mock-rackunit
  - raco doc-coverage arguments mock mock/rackunit
  - raco cover -f codecov -p arguments mock mock-rackunit
